name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux, x86_64-linux, x86_64-linux-musl, aarch64-linux, riscv64-linux ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build
      run: zig build -Doptimize=ReleaseSmall -Dtarget=${{ matrix.target }}

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: proxy-${{ matrix.target }}
        path: zig-out/bin/*

