name: release
on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: actions/create-release@v1
      id: create_release_step
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  upload_artifact:
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        target: [ x86-linux, x86_64-linux, x86_64-linux-musl, aarch64-linux, riscv64-linux ]
    runs-on: ubuntu-latest
    needs: create_release
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v1.3.0
      with:
        version: master

    - name: Build
      run: zig build -Doptimize=ReleaseSmall -Dtarget=${{ matrix.target }}

    - name: Rename
      run: mv zig-out/bin/proxy zig-out/bin/proxy-${{ matrix.target }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: zig-out/bin/proxy-${{ matrix.target }}

